# Generated by Django 5.0.6 on 2024-07-02 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=200)),
                ('debut', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release', models.DateField()),
                ('content', models.TextField(max_length=200)),
                ('Singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.singer')),
            ],
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
