# Generated by Django 5.0.6 on 2024-07-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_singer_song_delete_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
