# Generated by Django 5.0.6 on 2024-07-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
