# Generated by Django 5.0.6 on 2024-07-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_singer_name_alter_song_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='Singer',
            new_name='singer',
        ),
    ]
