# Generated by Django 5.0.6 on 2024-07-07 17:56

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_tag_singer_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.image_upload_path),
        ),
    ]
