# Generated by Django 5.0.6 on 2024-07-07 18:17

import django.db.models.deletion
import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_singer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=music.models.image_upload_path)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='music.singer')),
            ],
        ),
    ]
